#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-enforcer
Version  : 1.4.1
Release  : 1
URL      : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer-api/1.4.1/enforcer-api-1.4.1.jar
Source0  : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer-api/1.4.1/enforcer-api-1.4.1.jar
Source1  : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer-api/1.4.1/enforcer-api-1.4.1.pom
Source2  : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer-rules/1.4.1/enforcer-rules-1.4.1.jar
Source3  : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer-rules/1.4.1/enforcer-rules-1.4.1.pom
Source4  : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer/1.4.1/enforcer-1.4.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-enforcer-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-enforcer package.
Group: Data

%description data
data components for the mvn-enforcer package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/1.4.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/1.4.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/1.4.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/1.4.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/1.4.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/1.4.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/1.4.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/1.4.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer/1.4.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer/1.4.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/1.4.1/enforcer-api-1.4.1.jar
/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/1.4.1/enforcer-api-1.4.1.pom
/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/1.4.1/enforcer-rules-1.4.1.jar
/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/1.4.1/enforcer-rules-1.4.1.pom
/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer/1.4.1/enforcer-1.4.1.pom
