#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-enforcer
Version  : 1.4.1
Release  : 5
URL      : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer-api/1.4.1/enforcer-api-1.4.1.jar
Source0  : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer-api/1.4.1/enforcer-api-1.4.1.jar
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-enforcer-plugin/3.0.0-M1/maven-enforcer-plugin-3.0.0-M1.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-enforcer-plugin/3.0.0-M1/maven-enforcer-plugin-3.0.0-M1.pom
Source3  : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer-api/1.4.1/enforcer-api-1.4.1.pom
Source4  : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer-api/3.0.0-M1/enforcer-api-3.0.0-M1.jar
Source5  : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer-api/3.0.0-M1/enforcer-api-3.0.0-M1.pom
Source6  : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer-rules/1.4.1/enforcer-rules-1.4.1.jar
Source7  : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer-rules/1.4.1/enforcer-rules-1.4.1.pom
Source8  : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer-rules/3.0.0-M1/enforcer-rules-3.0.0-M1.jar
Source9  : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer-rules/3.0.0-M1/enforcer-rules-3.0.0-M1.pom
Source10  : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer/1.4.1/enforcer-1.4.1.pom
Source11  : https://repo1.maven.org/maven2/org/apache/maven/enforcer/enforcer/3.0.0-M1/enforcer-3.0.0-M1.pom
Source12  : https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-enforcer-plugin/1.4.1/maven-enforcer-plugin-1.4.1.jar
Source13  : https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-enforcer-plugin/1.4.1/maven-enforcer-plugin-1.4.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-enforcer-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-enforcer package.
Group: Data

%description data
data components for the mvn-enforcer package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/1.4.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/1.4.1/enforcer-api-1.4.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/3.0.0-M1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/3.0.0-M1/maven-enforcer-plugin-3.0.0-M1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/3.0.0-M1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/3.0.0-M1/maven-enforcer-plugin-3.0.0-M1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/1.4.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/1.4.1/enforcer-api-1.4.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/3.0.0-M1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/3.0.0-M1/enforcer-api-3.0.0-M1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/3.0.0-M1
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/3.0.0-M1/enforcer-api-3.0.0-M1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/1.4.1
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/1.4.1/enforcer-rules-1.4.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/1.4.1
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/1.4.1/enforcer-rules-1.4.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/3.0.0-M1
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/3.0.0-M1/enforcer-rules-3.0.0-M1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/3.0.0-M1
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/3.0.0-M1/enforcer-rules-3.0.0-M1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer/1.4.1
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer/1.4.1/enforcer-1.4.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer/3.0.0-M1
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer/3.0.0-M1/enforcer-3.0.0-M1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/1.4.1
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/1.4.1/maven-enforcer-plugin-1.4.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/1.4.1
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/1.4.1/maven-enforcer-plugin-1.4.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/1.4.1/enforcer-api-1.4.1.jar
/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/1.4.1/enforcer-api-1.4.1.pom
/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/3.0.0-M1/enforcer-api-3.0.0-M1.jar
/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-api/3.0.0-M1/enforcer-api-3.0.0-M1.pom
/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/1.4.1/enforcer-rules-1.4.1.jar
/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/1.4.1/enforcer-rules-1.4.1.pom
/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/3.0.0-M1/enforcer-rules-3.0.0-M1.jar
/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer-rules/3.0.0-M1/enforcer-rules-3.0.0-M1.pom
/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer/1.4.1/enforcer-1.4.1.pom
/usr/share/java/.m2/repository/org/apache/maven/enforcer/enforcer/3.0.0-M1/enforcer-3.0.0-M1.pom
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/1.4.1/maven-enforcer-plugin-1.4.1.jar
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/1.4.1/maven-enforcer-plugin-1.4.1.pom
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/3.0.0-M1/maven-enforcer-plugin-3.0.0-M1.jar
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/3.0.0-M1/maven-enforcer-plugin-3.0.0-M1.pom
